### ISSUE TITLE
Partial conversion / memory usage

### ISSUE THREAD

**Issue by gforcada** [gocept/zodb.py3migrate#2]
It would be useful to be able to ask to parse only X amount of objects so one can get some partial results and at the same time it would be useful to use this option with a memory profiler to get to understand why the memory usage just keeps growing and nothing is ever freed (in one Data.fs I have access to).

**Comment by icemac** [comment]
Version 0.2 has to new options:
- `--start` to start the analysis with a predefined OID.
- `--limit` to stop the analysis after a certain amount of seen OIDs.

Note that I split up the two functions previously united in the script `bin/zodb-py3migrate` into `bin/zodb-py3migrate-analyze``resp.``bin/zodb-py3migrate-convert``.
